{
	"jobConfig": {
		"name": "SILVER-GOLD ETL",
		"description": "",
		"role": "arn:aws:iam::166725663646:role/glue_role",
		"command": "glueetl",
		"version": "2.0",
		"runtime": null,
		"workerType": "G.1X",
		"numberOfWorkers": 10,
		"maxCapacity": 10,
		"jobRunQueuingEnabled": false,
		"maxRetries": 0,
		"timeout": 480,
		"maxConcurrentRuns": 1,
		"security": "none",
		"scriptName": "SILVER-GOLD ETL.py",
		"scriptLocation": "s3://aws-glue-assets-166725663646-us-east-2/scripts/",
		"language": "python-3",
		"spark": true,
		"sparkConfiguration": "standard",
		"jobParameters": [],
		"tags": [],
		"jobMode": "DEVELOPER_MODE",
		"createdOn": "2026-01-11T01:07:48.428Z",
		"developerMode": true,
		"connectionsList": [],
		"temporaryDirectory": "s3://aws-glue-assets-166725663646-us-east-2/temporary/",
		"glueHiveMetastore": true,
		"etlAutoTuning": true,
		"metrics": true,
		"observabilityMetrics": true,
		"bookmark": "job-bookmark-disable",
		"sparkPath": "s3://aws-glue-assets-166725663646-us-east-2/sparkHistoryLogs/",
		"flexExecution": false,
		"minFlexWorkers": null,
		"maintenanceWindow": null
	},
	"hasBeenSaved": false,
	"usageProfileName": null,
	"script": "# ---- GOLD BUILD (PySpark) ----\nfrom pyspark.sql import SparkSession, functions as F, window as W\n\nBUCKET = \"covid-analytics-niroj\"\nSILVER = f\"s3://{BUCKET}/covid/silver\"\nGOLD = f\"s3://{BUCKET}/covid/gold\"\n\nspark = SparkSession.builder.appName(\"covid-gold\").getOrCreate()\n\n# Read Silver outputs\ncases = spark.read.parquet(f\"{SILVER}/cases_standardized\")\ntests = spark.read.parquet(f\"{SILVER}/testing_standardized\")\n\n# dim_date\nall_dates = (cases.select(\"full_date\").union(tests.select(\"full_date\")).dropDuplicates())\ndim_date = (all_dates\n  .withColumn(\"date_id\", F.date_format(\"full_date\", \"yyyyMMdd\").cast(\"int\"))\n  .withColumn(\"year\", F.year(\"full_date\"))\n  .withColumn(\"month\", F.month(\"full_date\"))\n  .withColumn(\"day\", F.dayofmonth(\"full_date\"))\n  .withColumn(\"dow\", F.dayofweek(\"full_date\"))        # <-- FIXED HERE\n  .withColumn(\"is_weekend\", F.col(\"dow\").isin([1,7])) # 1=Sunday, 7=Saturday\n)\ndim_date.write.mode(\"overwrite\").parquet(f\"{GOLD}/dim_date\")\n\n# dim_state\ndim_state = cases.select(\"state_code\", \"state_name\").dropDuplicates()\ndim_state.write.mode(\"overwrite\").parquet(f\"{GOLD}/dim_state\")\n\n# fact_cases_state_daily\nw = W.Window.partitionBy(\"state_code\").orderBy(\"full_date\")\nfact_cases = (cases\n  .withColumn(\"date_id\", F.date_format(\"full_date\", \"yyyyMMdd\").cast(\"int\"))\n  .withColumn(\"new_cases\",  F.greatest(F.col(\"cases_cum\")  - F.lag(\"cases_cum\").over(w),  F.lit(0)))\n  .withColumn(\"new_deaths\", F.greatest(F.col(\"deaths_cum\") - F.lag(\"deaths_cum\").over(w), F.lit(0)))\n  .select(\"date_id\", \"state_code\", \"cases_cum\", \"deaths_cum\", \"new_cases\", \"new_deaths\")\n)\nfact_cases.write.mode(\"overwrite\").partitionBy(\"state_code\").parquet(f\"{GOLD}/fact_cases_state_daily\")\n\n# fact_testing_state_daily\nw2 = W.Window.partitionBy(\"state_code\").orderBy(\"full_date\")\nfact_tests = (tests\n  .withColumn(\"date_id\", F.date_format(\"full_date\", \"yyyyMMdd\").cast(\"int\"))\n  .withColumn(\"new_tests\", F.greatest(F.col(\"tests_total_cum\") - F.lag(\"tests_total_cum\").over(w2), F.lit(0)))\n  .withColumn(\"positivity_rate\", F.when(F.col(\"tests_total_cum\") > 0,\n                                       (F.col(\"tests_pos_cum\") / F.col(\"tests_total_cum\")).cast(\"double\")))\n  .select(\"date_id\", \"state_code\", \"tests_total_cum\", \"tests_pos_cum\", \"tests_neg_cum\", \"new_tests\", \"positivity_rate\")\n)\nfact_tests.write.mode(\"overwrite\").partitionBy(\"state_code\").parquet(f\"{GOLD}/fact_testing_state_daily\")\n\nprint(\"✅ Gold layer build complete\")\n"
}